<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ClCompile Include="cat.c" />
      <ClCompile Include="compare.c" />
      <ClCompile Include="crypto.c" />
      <ClCompile Include="sh.c" />
      <ClCompile Include="simple_call.c" />
      <ClCompile Include="simple_call2.c" />
      <ClCompile Include="sqlite_pre.c" />
      <ClCompile Include="TermText.c" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="util.wat" />
    </ItemGroup>
</Project>
