<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="../Wasm2CIl/Wasm2CIl.csproj" />
    </ItemGroup>

    <ItemGroup>
        <WatFile Include="WatFiles/w1.wat"/>
        <WatFile Include="WatFiles/w2.wat"/>
        <None Include="sqlite3.wasm">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <Target Name="WatToWasm" BeforeTargets="Build"
            Inputs="%(WatFile.Identity)"
            Outputs="$(OutputPath)%(WatFile.Filename).wasm">
        <Exec Command="wat2wasm %(WatFile.Identity) -o $(OutputPath)%(WatFile.Filename).wasm" />
    </Target>

</Project>
