<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>


        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Copyright>Copyright (c) 2025 Rolf Madsen. Licensed under the MIT License.</Copyright>


        <!-- NuGet metadata -->
        <PackageId>Wasm2IL</PackageId>
        <Version>0.1.0-alpha.4</Version>
        <Authors>Rolf Madsen</Authors>
        <Description>Wasm2IL: Convert WebAssembly modules into .NET.</Description>
        <PackageProjectUrl>https://github.com/rolfrm/Wasm2IL</PackageProjectUrl>
        <RepositoryUrl>https://github.com/rolfrm/Wasm2IL</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>wasm webassembly il dotnet cil</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>

    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <Optimize>false</Optimize>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    </ItemGroup>
    <ItemGroup>
      <None Include="..\README.md" Pack="true" PackagePath="" >
        <Link>README.md</Link>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    
</Project>
